spring:
  profiles:
    active: loacl

logging:
  config: classpath:log4j2.yml

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  batch:
    job:
      names: ${job.names=NONE}
    jdbc:
      initialize-schema: always

---
spring:
  profiles:
    active:
      on-profile: test
  jpa:
    database: h2